/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ORXToken__factory } from "./ORXToken__factory";
export { OracleBridge__factory } from "./OracleBridge__factory";
