/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IAIOracle,
  IAIOracleInterface,
} from "../../../contracts/interfaces/IAIOracle";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_market",
        type: "address",
      },
    ],
    name: "getAIResult",
    outputs: [
      {
        internalType: "uint256",
        name: "outcome",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "confidence",
        type: "uint256",
      },
      {
        internalType: "bool",
        name: "isSubmitted",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_market",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_predictedOutcome",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_confidence",
        type: "uint256",
      },
      {
        internalType: "string",
        name: "_evidence",
        type: "string",
      },
    ],
    name: "submitAIResult",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IAIOracle__factory {
  static readonly abi = _abi;
  static createInterface(): IAIOracleInterface {
    return new Interface(_abi) as IAIOracleInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IAIOracle {
    return new Contract(address, _abi, runner) as unknown as IAIOracle;
  }
}
