/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace AIOracle {
  export type AgentReportStruct = {
    agent: AddressLike;
    outcome: BigNumberish;
    confidence: BigNumberish;
    data: string;
    timestamp: BigNumberish;
  };

  export type AgentReportStructOutput = [
    agent: string,
    outcome: bigint,
    confidence: bigint,
    data: string,
    timestamp: bigint
  ] & {
    agent: string;
    outcome: bigint;
    confidence: bigint;
    data: string;
    timestamp: bigint;
  };
}

export interface AIOracleInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "agentReports"
      | "agentReputation"
      | "aiResults"
      | "authorizeAgent"
      | "authorizedAgents"
      | "consensusThreshold"
      | "deauthorizeAgent"
      | "forceConsensusCheck"
      | "getAIResult"
      | "getAgentReport"
      | "getMarketAgents"
      | "marketAgents"
      | "minimumAgents"
      | "minimumConfidence"
      | "owner"
      | "renounceOwnership"
      | "submitAIResult"
      | "submitManualResult"
      | "transferOwnership"
      | "updateAgentReputation"
      | "updateParameters"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AIResultSubmitted"
      | "AgentAuthorized"
      | "AgentDeauthorized"
      | "AgentReportSubmitted"
      | "ConsensusReached"
      | "OwnershipTransferred"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "agentReports",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "agentReputation",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "aiResults",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "authorizeAgent",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "authorizedAgents",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "consensusThreshold",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "deauthorizeAgent",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "forceConsensusCheck",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getAIResult",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getAgentReport",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getMarketAgents",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "marketAgents",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "minimumAgents",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "minimumConfidence",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "submitAIResult",
    values: [AddressLike, BigNumberish, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "submitManualResult",
    values: [AddressLike, BigNumberish, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateAgentReputation",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateParameters",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "agentReports",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "agentReputation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "aiResults", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "authorizeAgent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "authorizedAgents",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "consensusThreshold",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deauthorizeAgent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "forceConsensusCheck",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAIResult",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAgentReport",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMarketAgents",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "marketAgents",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "minimumAgents",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "minimumConfidence",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitAIResult",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitManualResult",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateAgentReputation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateParameters",
    data: BytesLike
  ): Result;
}

export namespace AIResultSubmittedEvent {
  export type InputTuple = [
    market: AddressLike,
    outcome: BigNumberish,
    confidence: BigNumberish,
    submitter: AddressLike
  ];
  export type OutputTuple = [
    market: string,
    outcome: bigint,
    confidence: bigint,
    submitter: string
  ];
  export interface OutputObject {
    market: string;
    outcome: bigint;
    confidence: bigint;
    submitter: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AgentAuthorizedEvent {
  export type InputTuple = [agent: AddressLike, reputation: BigNumberish];
  export type OutputTuple = [agent: string, reputation: bigint];
  export interface OutputObject {
    agent: string;
    reputation: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AgentDeauthorizedEvent {
  export type InputTuple = [agent: AddressLike];
  export type OutputTuple = [agent: string];
  export interface OutputObject {
    agent: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AgentReportSubmittedEvent {
  export type InputTuple = [
    market: AddressLike,
    agent: AddressLike,
    outcome: BigNumberish,
    confidence: BigNumberish
  ];
  export type OutputTuple = [
    market: string,
    agent: string,
    outcome: bigint,
    confidence: bigint
  ];
  export interface OutputObject {
    market: string;
    agent: string;
    outcome: bigint;
    confidence: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ConsensusReachedEvent {
  export type InputTuple = [
    market: AddressLike,
    outcome: BigNumberish,
    confidence: BigNumberish
  ];
  export type OutputTuple = [
    market: string,
    outcome: bigint,
    confidence: bigint
  ];
  export interface OutputObject {
    market: string;
    outcome: bigint;
    confidence: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AIOracle extends BaseContract {
  connect(runner?: ContractRunner | null): AIOracle;
  waitForDeployment(): Promise<this>;

  interface: AIOracleInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  agentReports: TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike],
    [
      [string, bigint, bigint, string, bigint] & {
        agent: string;
        outcome: bigint;
        confidence: bigint;
        data: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  agentReputation: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  aiResults: TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, bigint, bigint, boolean, string, string] & {
        predictedOutcome: bigint;
        confidence: bigint;
        timestamp: bigint;
        isSubmitted: boolean;
        evidence: string;
        submitter: string;
      }
    ],
    "view"
  >;

  authorizeAgent: TypedContractMethod<
    [_agent: AddressLike, _reputation: BigNumberish],
    [void],
    "nonpayable"
  >;

  authorizedAgents: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  consensusThreshold: TypedContractMethod<[], [bigint], "view">;

  deauthorizeAgent: TypedContractMethod<
    [_agent: AddressLike],
    [void],
    "nonpayable"
  >;

  forceConsensusCheck: TypedContractMethod<
    [_market: AddressLike],
    [void],
    "nonpayable"
  >;

  getAIResult: TypedContractMethod<
    [_market: AddressLike],
    [
      [bigint, bigint, boolean] & {
        outcome: bigint;
        confidence: bigint;
        isSubmitted: boolean;
      }
    ],
    "view"
  >;

  getAgentReport: TypedContractMethod<
    [_market: AddressLike, _agent: AddressLike],
    [AIOracle.AgentReportStructOutput],
    "view"
  >;

  getMarketAgents: TypedContractMethod<
    [_market: AddressLike],
    [string[]],
    "view"
  >;

  marketAgents: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  minimumAgents: TypedContractMethod<[], [bigint], "view">;

  minimumConfidence: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  submitAIResult: TypedContractMethod<
    [
      _market: AddressLike,
      _predictedOutcome: BigNumberish,
      _confidence: BigNumberish,
      _evidence: string
    ],
    [void],
    "nonpayable"
  >;

  submitManualResult: TypedContractMethod<
    [
      _market: AddressLike,
      _outcome: BigNumberish,
      _confidence: BigNumberish,
      _evidence: string
    ],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  updateAgentReputation: TypedContractMethod<
    [_agent: AddressLike, _newReputation: BigNumberish],
    [void],
    "nonpayable"
  >;

  updateParameters: TypedContractMethod<
    [
      _minimumConfidence: BigNumberish,
      _minimumAgents: BigNumberish,
      _consensusThreshold: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "agentReports"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike],
    [
      [string, bigint, bigint, string, bigint] & {
        agent: string;
        outcome: bigint;
        confidence: bigint;
        data: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "agentReputation"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "aiResults"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, bigint, bigint, boolean, string, string] & {
        predictedOutcome: bigint;
        confidence: bigint;
        timestamp: bigint;
        isSubmitted: boolean;
        evidence: string;
        submitter: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "authorizeAgent"
  ): TypedContractMethod<
    [_agent: AddressLike, _reputation: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "authorizedAgents"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "consensusThreshold"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "deauthorizeAgent"
  ): TypedContractMethod<[_agent: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "forceConsensusCheck"
  ): TypedContractMethod<[_market: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getAIResult"
  ): TypedContractMethod<
    [_market: AddressLike],
    [
      [bigint, bigint, boolean] & {
        outcome: bigint;
        confidence: bigint;
        isSubmitted: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAgentReport"
  ): TypedContractMethod<
    [_market: AddressLike, _agent: AddressLike],
    [AIOracle.AgentReportStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getMarketAgents"
  ): TypedContractMethod<[_market: AddressLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "marketAgents"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "minimumAgents"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "minimumConfidence"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "submitAIResult"
  ): TypedContractMethod<
    [
      _market: AddressLike,
      _predictedOutcome: BigNumberish,
      _confidence: BigNumberish,
      _evidence: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "submitManualResult"
  ): TypedContractMethod<
    [
      _market: AddressLike,
      _outcome: BigNumberish,
      _confidence: BigNumberish,
      _evidence: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateAgentReputation"
  ): TypedContractMethod<
    [_agent: AddressLike, _newReputation: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateParameters"
  ): TypedContractMethod<
    [
      _minimumConfidence: BigNumberish,
      _minimumAgents: BigNumberish,
      _consensusThreshold: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "AIResultSubmitted"
  ): TypedContractEvent<
    AIResultSubmittedEvent.InputTuple,
    AIResultSubmittedEvent.OutputTuple,
    AIResultSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "AgentAuthorized"
  ): TypedContractEvent<
    AgentAuthorizedEvent.InputTuple,
    AgentAuthorizedEvent.OutputTuple,
    AgentAuthorizedEvent.OutputObject
  >;
  getEvent(
    key: "AgentDeauthorized"
  ): TypedContractEvent<
    AgentDeauthorizedEvent.InputTuple,
    AgentDeauthorizedEvent.OutputTuple,
    AgentDeauthorizedEvent.OutputObject
  >;
  getEvent(
    key: "AgentReportSubmitted"
  ): TypedContractEvent<
    AgentReportSubmittedEvent.InputTuple,
    AgentReportSubmittedEvent.OutputTuple,
    AgentReportSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "ConsensusReached"
  ): TypedContractEvent<
    ConsensusReachedEvent.InputTuple,
    ConsensusReachedEvent.OutputTuple,
    ConsensusReachedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "AIResultSubmitted(address,uint256,uint256,address)": TypedContractEvent<
      AIResultSubmittedEvent.InputTuple,
      AIResultSubmittedEvent.OutputTuple,
      AIResultSubmittedEvent.OutputObject
    >;
    AIResultSubmitted: TypedContractEvent<
      AIResultSubmittedEvent.InputTuple,
      AIResultSubmittedEvent.OutputTuple,
      AIResultSubmittedEvent.OutputObject
    >;

    "AgentAuthorized(address,uint256)": TypedContractEvent<
      AgentAuthorizedEvent.InputTuple,
      AgentAuthorizedEvent.OutputTuple,
      AgentAuthorizedEvent.OutputObject
    >;
    AgentAuthorized: TypedContractEvent<
      AgentAuthorizedEvent.InputTuple,
      AgentAuthorizedEvent.OutputTuple,
      AgentAuthorizedEvent.OutputObject
    >;

    "AgentDeauthorized(address)": TypedContractEvent<
      AgentDeauthorizedEvent.InputTuple,
      AgentDeauthorizedEvent.OutputTuple,
      AgentDeauthorizedEvent.OutputObject
    >;
    AgentDeauthorized: TypedContractEvent<
      AgentDeauthorizedEvent.InputTuple,
      AgentDeauthorizedEvent.OutputTuple,
      AgentDeauthorizedEvent.OutputObject
    >;

    "AgentReportSubmitted(address,address,uint256,uint256)": TypedContractEvent<
      AgentReportSubmittedEvent.InputTuple,
      AgentReportSubmittedEvent.OutputTuple,
      AgentReportSubmittedEvent.OutputObject
    >;
    AgentReportSubmitted: TypedContractEvent<
      AgentReportSubmittedEvent.InputTuple,
      AgentReportSubmittedEvent.OutputTuple,
      AgentReportSubmittedEvent.OutputObject
    >;

    "ConsensusReached(address,uint256,uint256)": TypedContractEvent<
      ConsensusReachedEvent.InputTuple,
      ConsensusReachedEvent.OutputTuple,
      ConsensusReachedEvent.OutputObject
    >;
    ConsensusReached: TypedContractEvent<
      ConsensusReachedEvent.InputTuple,
      ConsensusReachedEvent.OutputTuple,
      ConsensusReachedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
