/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace DisputeResolution {
  export type DisputeStruct = {
    market: AddressLike;
    disputer: AddressLike;
    disputedOutcome: BigNumberish;
    proposedOutcome: BigNumberish;
    reason: string;
    disputeBond: BigNumberish;
    createdAt: BigNumberish;
    votingEndsAt: BigNumberish;
    status: BigNumberish;
    upholdVotes: BigNumberish;
    overturnVotes: BigNumberish;
    totalVotingPower: BigNumberish;
    resolved: boolean;
    finalOutcome: BigNumberish;
  };

  export type DisputeStructOutput = [
    market: string,
    disputer: string,
    disputedOutcome: bigint,
    proposedOutcome: bigint,
    reason: string,
    disputeBond: bigint,
    createdAt: bigint,
    votingEndsAt: bigint,
    status: bigint,
    upholdVotes: bigint,
    overturnVotes: bigint,
    totalVotingPower: bigint,
    resolved: boolean,
    finalOutcome: bigint
  ] & {
    market: string;
    disputer: string;
    disputedOutcome: bigint;
    proposedOutcome: bigint;
    reason: string;
    disputeBond: bigint;
    createdAt: bigint;
    votingEndsAt: bigint;
    status: bigint;
    upholdVotes: bigint;
    overturnVotes: bigint;
    totalVotingPower: bigint;
    resolved: boolean;
    finalOutcome: bigint;
  };

  export type VoteStruct = {
    choice: BigNumberish;
    votingPower: BigNumberish;
    timestamp: BigNumberish;
    claimed: boolean;
  };

  export type VoteStructOutput = [
    choice: bigint,
    votingPower: bigint,
    timestamp: bigint,
    claimed: boolean
  ] & {
    choice: bigint;
    votingPower: bigint;
    timestamp: bigint;
    claimed: boolean;
  };
}

export interface DisputeResolutionInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "canVote"
      | "claimVotingReward"
      | "disputeCounter"
      | "disputeVoters"
      | "disputes"
      | "emergencyWithdraw"
      | "finalizeDispute"
      | "getActiveDisputes"
      | "getDispute"
      | "getDisputeVoters"
      | "getTotalDisputes"
      | "getVote"
      | "minimumDisputeBond"
      | "minimumVotingPower"
      | "openDispute"
      | "orxToken"
      | "owner"
      | "quorumThreshold"
      | "renounceOwnership"
      | "stakingContract"
      | "transferOwnership"
      | "updateParameters"
      | "voteOnDispute"
      | "votes"
      | "votingPeriod"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DisputeOpened"
      | "DisputeResolved"
      | "OwnershipTransferred"
      | "RewardsDistributed"
      | "VoteCast"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "canVote",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "claimVotingReward",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "disputeCounter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "disputeVoters",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "disputes",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyWithdraw",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "finalizeDispute",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getActiveDisputes",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getDispute",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getDisputeVoters",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalDisputes",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getVote",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "minimumDisputeBond",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "minimumVotingPower",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "openDispute",
    values: [AddressLike, BigNumberish, BigNumberish, string]
  ): string;
  encodeFunctionData(functionFragment: "orxToken", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "quorumThreshold",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "stakingContract",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateParameters",
    values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "voteOnDispute",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "votes",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "votingPeriod",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "canVote", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "claimVotingReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "disputeCounter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "disputeVoters",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "disputes", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "emergencyWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "finalizeDispute",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getActiveDisputes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getDispute", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getDisputeVoters",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalDisputes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getVote", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "minimumDisputeBond",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "minimumVotingPower",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "openDispute",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "orxToken", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "quorumThreshold",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "stakingContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateParameters",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "voteOnDispute",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "votes", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "votingPeriod",
    data: BytesLike
  ): Result;
}

export namespace DisputeOpenedEvent {
  export type InputTuple = [
    disputeId: BigNumberish,
    market: AddressLike,
    disputer: AddressLike,
    disputedOutcome: BigNumberish,
    proposedOutcome: BigNumberish
  ];
  export type OutputTuple = [
    disputeId: bigint,
    market: string,
    disputer: string,
    disputedOutcome: bigint,
    proposedOutcome: bigint
  ];
  export interface OutputObject {
    disputeId: bigint;
    market: string;
    disputer: string;
    disputedOutcome: bigint;
    proposedOutcome: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DisputeResolvedEvent {
  export type InputTuple = [
    disputeId: BigNumberish,
    upheld: boolean,
    finalOutcome: BigNumberish
  ];
  export type OutputTuple = [
    disputeId: bigint,
    upheld: boolean,
    finalOutcome: bigint
  ];
  export interface OutputObject {
    disputeId: bigint;
    upheld: boolean;
    finalOutcome: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RewardsDistributedEvent {
  export type InputTuple = [
    disputeId: BigNumberish,
    totalRewards: BigNumberish
  ];
  export type OutputTuple = [disputeId: bigint, totalRewards: bigint];
  export interface OutputObject {
    disputeId: bigint;
    totalRewards: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VoteCastEvent {
  export type InputTuple = [
    disputeId: BigNumberish,
    voter: AddressLike,
    choice: BigNumberish,
    votingPower: BigNumberish
  ];
  export type OutputTuple = [
    disputeId: bigint,
    voter: string,
    choice: bigint,
    votingPower: bigint
  ];
  export interface OutputObject {
    disputeId: bigint;
    voter: string;
    choice: bigint;
    votingPower: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface DisputeResolution extends BaseContract {
  connect(runner?: ContractRunner | null): DisputeResolution;
  waitForDeployment(): Promise<this>;

  interface: DisputeResolutionInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  canVote: TypedContractMethod<
    [_disputeId: BigNumberish, _voter: AddressLike],
    [boolean],
    "view"
  >;

  claimVotingReward: TypedContractMethod<
    [_disputeId: BigNumberish],
    [void],
    "nonpayable"
  >;

  disputeCounter: TypedContractMethod<[], [bigint], "view">;

  disputeVoters: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [string],
    "view"
  >;

  disputes: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        string,
        bigint,
        bigint,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        bigint
      ] & {
        market: string;
        disputer: string;
        disputedOutcome: bigint;
        proposedOutcome: bigint;
        reason: string;
        disputeBond: bigint;
        createdAt: bigint;
        votingEndsAt: bigint;
        status: bigint;
        upholdVotes: bigint;
        overturnVotes: bigint;
        totalVotingPower: bigint;
        resolved: boolean;
        finalOutcome: bigint;
      }
    ],
    "view"
  >;

  emergencyWithdraw: TypedContractMethod<[], [void], "nonpayable">;

  finalizeDispute: TypedContractMethod<
    [_disputeId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getActiveDisputes: TypedContractMethod<[], [bigint[]], "view">;

  getDispute: TypedContractMethod<
    [_disputeId: BigNumberish],
    [DisputeResolution.DisputeStructOutput],
    "view"
  >;

  getDisputeVoters: TypedContractMethod<
    [_disputeId: BigNumberish],
    [string[]],
    "view"
  >;

  getTotalDisputes: TypedContractMethod<[], [bigint], "view">;

  getVote: TypedContractMethod<
    [_disputeId: BigNumberish, _voter: AddressLike],
    [DisputeResolution.VoteStructOutput],
    "view"
  >;

  minimumDisputeBond: TypedContractMethod<[], [bigint], "view">;

  minimumVotingPower: TypedContractMethod<[], [bigint], "view">;

  openDispute: TypedContractMethod<
    [
      _market: AddressLike,
      _disputedOutcome: BigNumberish,
      _proposedOutcome: BigNumberish,
      _reason: string
    ],
    [bigint],
    "payable"
  >;

  orxToken: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  quorumThreshold: TypedContractMethod<[], [bigint], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  stakingContract: TypedContractMethod<[], [string], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  updateParameters: TypedContractMethod<
    [
      _minimumDisputeBond: BigNumberish,
      _votingPeriod: BigNumberish,
      _quorumThreshold: BigNumberish,
      _minimumVotingPower: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  voteOnDispute: TypedContractMethod<
    [_disputeId: BigNumberish, _choice: BigNumberish],
    [void],
    "nonpayable"
  >;

  votes: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [
      [bigint, bigint, bigint, boolean] & {
        choice: bigint;
        votingPower: bigint;
        timestamp: bigint;
        claimed: boolean;
      }
    ],
    "view"
  >;

  votingPeriod: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "canVote"
  ): TypedContractMethod<
    [_disputeId: BigNumberish, _voter: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "claimVotingReward"
  ): TypedContractMethod<[_disputeId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "disputeCounter"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "disputeVoters"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "disputes"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        string,
        bigint,
        bigint,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        bigint
      ] & {
        market: string;
        disputer: string;
        disputedOutcome: bigint;
        proposedOutcome: bigint;
        reason: string;
        disputeBond: bigint;
        createdAt: bigint;
        votingEndsAt: bigint;
        status: bigint;
        upholdVotes: bigint;
        overturnVotes: bigint;
        totalVotingPower: bigint;
        resolved: boolean;
        finalOutcome: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "emergencyWithdraw"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "finalizeDispute"
  ): TypedContractMethod<[_disputeId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getActiveDisputes"
  ): TypedContractMethod<[], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getDispute"
  ): TypedContractMethod<
    [_disputeId: BigNumberish],
    [DisputeResolution.DisputeStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getDisputeVoters"
  ): TypedContractMethod<[_disputeId: BigNumberish], [string[]], "view">;
  getFunction(
    nameOrSignature: "getTotalDisputes"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getVote"
  ): TypedContractMethod<
    [_disputeId: BigNumberish, _voter: AddressLike],
    [DisputeResolution.VoteStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "minimumDisputeBond"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "minimumVotingPower"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "openDispute"
  ): TypedContractMethod<
    [
      _market: AddressLike,
      _disputedOutcome: BigNumberish,
      _proposedOutcome: BigNumberish,
      _reason: string
    ],
    [bigint],
    "payable"
  >;
  getFunction(
    nameOrSignature: "orxToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "quorumThreshold"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "stakingContract"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateParameters"
  ): TypedContractMethod<
    [
      _minimumDisputeBond: BigNumberish,
      _votingPeriod: BigNumberish,
      _quorumThreshold: BigNumberish,
      _minimumVotingPower: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "voteOnDispute"
  ): TypedContractMethod<
    [_disputeId: BigNumberish, _choice: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "votes"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [
      [bigint, bigint, bigint, boolean] & {
        choice: bigint;
        votingPower: bigint;
        timestamp: bigint;
        claimed: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "votingPeriod"
  ): TypedContractMethod<[], [bigint], "view">;

  getEvent(
    key: "DisputeOpened"
  ): TypedContractEvent<
    DisputeOpenedEvent.InputTuple,
    DisputeOpenedEvent.OutputTuple,
    DisputeOpenedEvent.OutputObject
  >;
  getEvent(
    key: "DisputeResolved"
  ): TypedContractEvent<
    DisputeResolvedEvent.InputTuple,
    DisputeResolvedEvent.OutputTuple,
    DisputeResolvedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "RewardsDistributed"
  ): TypedContractEvent<
    RewardsDistributedEvent.InputTuple,
    RewardsDistributedEvent.OutputTuple,
    RewardsDistributedEvent.OutputObject
  >;
  getEvent(
    key: "VoteCast"
  ): TypedContractEvent<
    VoteCastEvent.InputTuple,
    VoteCastEvent.OutputTuple,
    VoteCastEvent.OutputObject
  >;

  filters: {
    "DisputeOpened(uint256,address,address,uint256,uint256)": TypedContractEvent<
      DisputeOpenedEvent.InputTuple,
      DisputeOpenedEvent.OutputTuple,
      DisputeOpenedEvent.OutputObject
    >;
    DisputeOpened: TypedContractEvent<
      DisputeOpenedEvent.InputTuple,
      DisputeOpenedEvent.OutputTuple,
      DisputeOpenedEvent.OutputObject
    >;

    "DisputeResolved(uint256,bool,uint256)": TypedContractEvent<
      DisputeResolvedEvent.InputTuple,
      DisputeResolvedEvent.OutputTuple,
      DisputeResolvedEvent.OutputObject
    >;
    DisputeResolved: TypedContractEvent<
      DisputeResolvedEvent.InputTuple,
      DisputeResolvedEvent.OutputTuple,
      DisputeResolvedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "RewardsDistributed(uint256,uint256)": TypedContractEvent<
      RewardsDistributedEvent.InputTuple,
      RewardsDistributedEvent.OutputTuple,
      RewardsDistributedEvent.OutputObject
    >;
    RewardsDistributed: TypedContractEvent<
      RewardsDistributedEvent.InputTuple,
      RewardsDistributedEvent.OutputTuple,
      RewardsDistributedEvent.OutputObject
    >;

    "VoteCast(uint256,address,uint8,uint256)": TypedContractEvent<
      VoteCastEvent.InputTuple,
      VoteCastEvent.OutputTuple,
      VoteCastEvent.OutputObject
    >;
    VoteCast: TypedContractEvent<
      VoteCastEvent.InputTuple,
      VoteCastEvent.OutputTuple,
      VoteCastEvent.OutputObject
    >;
  };
}
