/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace GovernanceDAO {
  export type ProposalStruct = {
    id: BigNumberish;
    proposer: AddressLike;
    title: string;
    description: string;
    votesFor: BigNumberish;
    votesAgainst: BigNumberish;
    votesAbstain: BigNumberish;
    totalVotingPower: BigNumberish;
    createdAt: BigNumberish;
    votingStartsAt: BigNumberish;
    votingEndsAt: BigNumberish;
    status: BigNumberish;
    quorumRequired: BigNumberish;
    approvalThreshold: BigNumberish;
    executed: boolean;
    executionData: BytesLike;
    targetContract: AddressLike;
  };

  export type ProposalStructOutput = [
    id: bigint,
    proposer: string,
    title: string,
    description: string,
    votesFor: bigint,
    votesAgainst: bigint,
    votesAbstain: bigint,
    totalVotingPower: bigint,
    createdAt: bigint,
    votingStartsAt: bigint,
    votingEndsAt: bigint,
    status: bigint,
    quorumRequired: bigint,
    approvalThreshold: bigint,
    executed: boolean,
    executionData: string,
    targetContract: string
  ] & {
    id: bigint;
    proposer: string;
    title: string;
    description: string;
    votesFor: bigint;
    votesAgainst: bigint;
    votesAbstain: bigint;
    totalVotingPower: bigint;
    createdAt: bigint;
    votingStartsAt: bigint;
    votingEndsAt: bigint;
    status: bigint;
    quorumRequired: bigint;
    approvalThreshold: bigint;
    executed: boolean;
    executionData: string;
    targetContract: string;
  };

  export type VoteStruct = {
    choice: BigNumberish;
    votingPower: BigNumberish;
    timestamp: BigNumberish;
  };

  export type VoteStructOutput = [
    choice: bigint,
    votingPower: bigint,
    timestamp: bigint
  ] & { choice: bigint; votingPower: bigint; timestamp: bigint };
}

export interface GovernanceDAOInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "approvalPercentage"
      | "canPropose"
      | "canVote"
      | "cancelProposal"
      | "castVote"
      | "createProposal"
      | "executeProposal"
      | "finalizeProposal"
      | "getActiveProposals"
      | "getProposal"
      | "getProposalVoters"
      | "getProposalsByStatus"
      | "getTotalProposals"
      | "getVote"
      | "getVotingPower"
      | "orxToken"
      | "owner"
      | "proposalCounter"
      | "proposalThreshold"
      | "proposalVoters"
      | "proposals"
      | "quorumPercentage"
      | "renounceOwnership"
      | "stakingContract"
      | "transferOwnership"
      | "updateParameters"
      | "votes"
      | "votingDelay"
      | "votingPeriod"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "OwnershipTransferred"
      | "ProposalCancelled"
      | "ProposalCreated"
      | "ProposalExecuted"
      | "ProposalStatusChanged"
      | "VoteCast"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "approvalPercentage",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "canPropose",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "canVote",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelProposal",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "castVote",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createProposal",
    values: [string, string, AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "executeProposal",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "finalizeProposal",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getActiveProposals",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getProposal",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getProposalVoters",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getProposalsByStatus",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalProposals",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getVote",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getVotingPower",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "orxToken", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "proposalCounter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "proposalThreshold",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "proposalVoters",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "proposals",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "quorumPercentage",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "stakingContract",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateParameters",
    values: [
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "votes",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "votingDelay",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "votingPeriod",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "approvalPercentage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "canPropose", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "canVote", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "cancelProposal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "castVote", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "createProposal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeProposal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "finalizeProposal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getActiveProposals",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getProposal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getProposalVoters",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getProposalsByStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalProposals",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getVote", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getVotingPower",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "orxToken", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "proposalCounter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "proposalThreshold",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "proposalVoters",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "proposals", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "quorumPercentage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "stakingContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateParameters",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "votes", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "votingDelay",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "votingPeriod",
    data: BytesLike
  ): Result;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProposalCancelledEvent {
  export type InputTuple = [proposalId: BigNumberish];
  export type OutputTuple = [proposalId: bigint];
  export interface OutputObject {
    proposalId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProposalCreatedEvent {
  export type InputTuple = [
    proposalId: BigNumberish,
    proposer: AddressLike,
    title: string,
    votingStartsAt: BigNumberish,
    votingEndsAt: BigNumberish
  ];
  export type OutputTuple = [
    proposalId: bigint,
    proposer: string,
    title: string,
    votingStartsAt: bigint,
    votingEndsAt: bigint
  ];
  export interface OutputObject {
    proposalId: bigint;
    proposer: string;
    title: string;
    votingStartsAt: bigint;
    votingEndsAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProposalExecutedEvent {
  export type InputTuple = [proposalId: BigNumberish, success: boolean];
  export type OutputTuple = [proposalId: bigint, success: boolean];
  export interface OutputObject {
    proposalId: bigint;
    success: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProposalStatusChangedEvent {
  export type InputTuple = [proposalId: BigNumberish, newStatus: BigNumberish];
  export type OutputTuple = [proposalId: bigint, newStatus: bigint];
  export interface OutputObject {
    proposalId: bigint;
    newStatus: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VoteCastEvent {
  export type InputTuple = [
    proposalId: BigNumberish,
    voter: AddressLike,
    choice: BigNumberish,
    votingPower: BigNumberish
  ];
  export type OutputTuple = [
    proposalId: bigint,
    voter: string,
    choice: bigint,
    votingPower: bigint
  ];
  export interface OutputObject {
    proposalId: bigint;
    voter: string;
    choice: bigint;
    votingPower: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface GovernanceDAO extends BaseContract {
  connect(runner?: ContractRunner | null): GovernanceDAO;
  waitForDeployment(): Promise<this>;

  interface: GovernanceDAOInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  approvalPercentage: TypedContractMethod<[], [bigint], "view">;

  canPropose: TypedContractMethod<[_proposer: AddressLike], [boolean], "view">;

  canVote: TypedContractMethod<
    [_proposalId: BigNumberish, _voter: AddressLike],
    [boolean],
    "view"
  >;

  cancelProposal: TypedContractMethod<
    [_proposalId: BigNumberish],
    [void],
    "nonpayable"
  >;

  castVote: TypedContractMethod<
    [_proposalId: BigNumberish, _choice: BigNumberish],
    [void],
    "nonpayable"
  >;

  createProposal: TypedContractMethod<
    [
      _title: string,
      _description: string,
      _targetContract: AddressLike,
      _executionData: BytesLike
    ],
    [bigint],
    "nonpayable"
  >;

  executeProposal: TypedContractMethod<
    [_proposalId: BigNumberish],
    [void],
    "nonpayable"
  >;

  finalizeProposal: TypedContractMethod<
    [_proposalId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getActiveProposals: TypedContractMethod<[], [bigint[]], "view">;

  getProposal: TypedContractMethod<
    [_proposalId: BigNumberish],
    [GovernanceDAO.ProposalStructOutput],
    "view"
  >;

  getProposalVoters: TypedContractMethod<
    [_proposalId: BigNumberish],
    [string[]],
    "view"
  >;

  getProposalsByStatus: TypedContractMethod<
    [_status: BigNumberish],
    [bigint[]],
    "view"
  >;

  getTotalProposals: TypedContractMethod<[], [bigint], "view">;

  getVote: TypedContractMethod<
    [_proposalId: BigNumberish, _voter: AddressLike],
    [GovernanceDAO.VoteStructOutput],
    "view"
  >;

  getVotingPower: TypedContractMethod<[_voter: AddressLike], [bigint], "view">;

  orxToken: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  proposalCounter: TypedContractMethod<[], [bigint], "view">;

  proposalThreshold: TypedContractMethod<[], [bigint], "view">;

  proposalVoters: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [string],
    "view"
  >;

  proposals: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        string,
        string
      ] & {
        id: bigint;
        proposer: string;
        title: string;
        description: string;
        votesFor: bigint;
        votesAgainst: bigint;
        votesAbstain: bigint;
        totalVotingPower: bigint;
        createdAt: bigint;
        votingStartsAt: bigint;
        votingEndsAt: bigint;
        status: bigint;
        quorumRequired: bigint;
        approvalThreshold: bigint;
        executed: boolean;
        executionData: string;
        targetContract: string;
      }
    ],
    "view"
  >;

  quorumPercentage: TypedContractMethod<[], [bigint], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  stakingContract: TypedContractMethod<[], [string], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  updateParameters: TypedContractMethod<
    [
      _proposalThreshold: BigNumberish,
      _votingDelay: BigNumberish,
      _votingPeriod: BigNumberish,
      _quorumPercentage: BigNumberish,
      _approvalPercentage: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  votes: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [
      [bigint, bigint, bigint] & {
        choice: bigint;
        votingPower: bigint;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  votingDelay: TypedContractMethod<[], [bigint], "view">;

  votingPeriod: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "approvalPercentage"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "canPropose"
  ): TypedContractMethod<[_proposer: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "canVote"
  ): TypedContractMethod<
    [_proposalId: BigNumberish, _voter: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "cancelProposal"
  ): TypedContractMethod<[_proposalId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "castVote"
  ): TypedContractMethod<
    [_proposalId: BigNumberish, _choice: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createProposal"
  ): TypedContractMethod<
    [
      _title: string,
      _description: string,
      _targetContract: AddressLike,
      _executionData: BytesLike
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "executeProposal"
  ): TypedContractMethod<[_proposalId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "finalizeProposal"
  ): TypedContractMethod<[_proposalId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getActiveProposals"
  ): TypedContractMethod<[], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getProposal"
  ): TypedContractMethod<
    [_proposalId: BigNumberish],
    [GovernanceDAO.ProposalStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getProposalVoters"
  ): TypedContractMethod<[_proposalId: BigNumberish], [string[]], "view">;
  getFunction(
    nameOrSignature: "getProposalsByStatus"
  ): TypedContractMethod<[_status: BigNumberish], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getTotalProposals"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getVote"
  ): TypedContractMethod<
    [_proposalId: BigNumberish, _voter: AddressLike],
    [GovernanceDAO.VoteStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getVotingPower"
  ): TypedContractMethod<[_voter: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "orxToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "proposalCounter"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "proposalThreshold"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "proposalVoters"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "proposals"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        string,
        string
      ] & {
        id: bigint;
        proposer: string;
        title: string;
        description: string;
        votesFor: bigint;
        votesAgainst: bigint;
        votesAbstain: bigint;
        totalVotingPower: bigint;
        createdAt: bigint;
        votingStartsAt: bigint;
        votingEndsAt: bigint;
        status: bigint;
        quorumRequired: bigint;
        approvalThreshold: bigint;
        executed: boolean;
        executionData: string;
        targetContract: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "quorumPercentage"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "stakingContract"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateParameters"
  ): TypedContractMethod<
    [
      _proposalThreshold: BigNumberish,
      _votingDelay: BigNumberish,
      _votingPeriod: BigNumberish,
      _quorumPercentage: BigNumberish,
      _approvalPercentage: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "votes"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [
      [bigint, bigint, bigint] & {
        choice: bigint;
        votingPower: bigint;
        timestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "votingDelay"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "votingPeriod"
  ): TypedContractMethod<[], [bigint], "view">;

  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "ProposalCancelled"
  ): TypedContractEvent<
    ProposalCancelledEvent.InputTuple,
    ProposalCancelledEvent.OutputTuple,
    ProposalCancelledEvent.OutputObject
  >;
  getEvent(
    key: "ProposalCreated"
  ): TypedContractEvent<
    ProposalCreatedEvent.InputTuple,
    ProposalCreatedEvent.OutputTuple,
    ProposalCreatedEvent.OutputObject
  >;
  getEvent(
    key: "ProposalExecuted"
  ): TypedContractEvent<
    ProposalExecutedEvent.InputTuple,
    ProposalExecutedEvent.OutputTuple,
    ProposalExecutedEvent.OutputObject
  >;
  getEvent(
    key: "ProposalStatusChanged"
  ): TypedContractEvent<
    ProposalStatusChangedEvent.InputTuple,
    ProposalStatusChangedEvent.OutputTuple,
    ProposalStatusChangedEvent.OutputObject
  >;
  getEvent(
    key: "VoteCast"
  ): TypedContractEvent<
    VoteCastEvent.InputTuple,
    VoteCastEvent.OutputTuple,
    VoteCastEvent.OutputObject
  >;

  filters: {
    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "ProposalCancelled(uint256)": TypedContractEvent<
      ProposalCancelledEvent.InputTuple,
      ProposalCancelledEvent.OutputTuple,
      ProposalCancelledEvent.OutputObject
    >;
    ProposalCancelled: TypedContractEvent<
      ProposalCancelledEvent.InputTuple,
      ProposalCancelledEvent.OutputTuple,
      ProposalCancelledEvent.OutputObject
    >;

    "ProposalCreated(uint256,address,string,uint256,uint256)": TypedContractEvent<
      ProposalCreatedEvent.InputTuple,
      ProposalCreatedEvent.OutputTuple,
      ProposalCreatedEvent.OutputObject
    >;
    ProposalCreated: TypedContractEvent<
      ProposalCreatedEvent.InputTuple,
      ProposalCreatedEvent.OutputTuple,
      ProposalCreatedEvent.OutputObject
    >;

    "ProposalExecuted(uint256,bool)": TypedContractEvent<
      ProposalExecutedEvent.InputTuple,
      ProposalExecutedEvent.OutputTuple,
      ProposalExecutedEvent.OutputObject
    >;
    ProposalExecuted: TypedContractEvent<
      ProposalExecutedEvent.InputTuple,
      ProposalExecutedEvent.OutputTuple,
      ProposalExecutedEvent.OutputObject
    >;

    "ProposalStatusChanged(uint256,uint8)": TypedContractEvent<
      ProposalStatusChangedEvent.InputTuple,
      ProposalStatusChangedEvent.OutputTuple,
      ProposalStatusChangedEvent.OutputObject
    >;
    ProposalStatusChanged: TypedContractEvent<
      ProposalStatusChangedEvent.InputTuple,
      ProposalStatusChangedEvent.OutputTuple,
      ProposalStatusChangedEvent.OutputObject
    >;

    "VoteCast(uint256,address,uint8,uint256)": TypedContractEvent<
      VoteCastEvent.InputTuple,
      VoteCastEvent.OutputTuple,
      VoteCastEvent.OutputObject
    >;
    VoteCast: TypedContractEvent<
      VoteCastEvent.InputTuple,
      VoteCastEvent.OutputTuple,
      VoteCastEvent.OutputObject
    >;
  };
}
