/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace OracleBridge {
  export type OracleStruct = {
    oracle: AddressLike;
    isActive: boolean;
    stake: BigNumberish;
    reputation: BigNumberish;
    totalResolutions: BigNumberish;
    correctResolutions: BigNumberish;
  };

  export type OracleStructOutput = [
    oracle: string,
    isActive: boolean,
    stake: bigint,
    reputation: bigint,
    totalResolutions: bigint,
    correctResolutions: bigint
  ] & {
    oracle: string;
    isActive: boolean;
    stake: bigint;
    reputation: bigint;
    totalResolutions: bigint;
    correctResolutions: bigint;
  };

  export type ResolutionStruct = {
    marketId: BigNumberish;
    outcome: BytesLike;
    confidence: BigNumberish;
    timestamp: BigNumberish;
    disputed: boolean;
    finalized: boolean;
  };

  export type ResolutionStructOutput = [
    marketId: bigint,
    outcome: string,
    confidence: bigint,
    timestamp: bigint,
    disputed: boolean,
    finalized: boolean
  ] & {
    marketId: bigint;
    outcome: string;
    confidence: bigint;
    timestamp: bigint;
    disputed: boolean;
    finalized: boolean;
  };
}

export interface OracleBridgeInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "CONSENSUS_THRESHOLD"
      | "MIN_ORACLES"
      | "MIN_STAKE"
      | "deactivateOracle"
      | "getActiveOraclesCount"
      | "getOracle"
      | "getResolution"
      | "marketOracles"
      | "oracleVotes"
      | "oracles"
      | "orxToken"
      | "owner"
      | "raiseDispute"
      | "registerOracle"
      | "registeredOracles"
      | "renounceOwnership"
      | "resolutions"
      | "submitResolution"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DisputeRaised"
      | "OracleDeactivated"
      | "OracleRegistered"
      | "OwnershipTransferred"
      | "ResolutionFinalized"
      | "ResolutionSubmitted"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "CONSENSUS_THRESHOLD",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MIN_ORACLES",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "MIN_STAKE", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "deactivateOracle",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getActiveOraclesCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getOracle",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getResolution",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "marketOracles",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "oracleVotes",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "oracles",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "orxToken", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "raiseDispute",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "registerOracle",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "registeredOracles",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "resolutions",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "submitResolution",
    values: [BigNumberish, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "CONSENSUS_THRESHOLD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MIN_ORACLES",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "MIN_STAKE", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "deactivateOracle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getActiveOraclesCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getOracle", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getResolution",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "marketOracles",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "oracleVotes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "oracles", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "orxToken", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "raiseDispute",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerOracle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registeredOracles",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "resolutions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitResolution",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace DisputeRaisedEvent {
  export type InputTuple = [marketId: BigNumberish, disputer: AddressLike];
  export type OutputTuple = [marketId: bigint, disputer: string];
  export interface OutputObject {
    marketId: bigint;
    disputer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OracleDeactivatedEvent {
  export type InputTuple = [oracle: AddressLike];
  export type OutputTuple = [oracle: string];
  export interface OutputObject {
    oracle: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OracleRegisteredEvent {
  export type InputTuple = [oracle: AddressLike, stake: BigNumberish];
  export type OutputTuple = [oracle: string, stake: bigint];
  export interface OutputObject {
    oracle: string;
    stake: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ResolutionFinalizedEvent {
  export type InputTuple = [marketId: BigNumberish, outcome: BytesLike];
  export type OutputTuple = [marketId: bigint, outcome: string];
  export interface OutputObject {
    marketId: bigint;
    outcome: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ResolutionSubmittedEvent {
  export type InputTuple = [
    marketId: BigNumberish,
    oracle: AddressLike,
    outcome: BytesLike
  ];
  export type OutputTuple = [marketId: bigint, oracle: string, outcome: string];
  export interface OutputObject {
    marketId: bigint;
    oracle: string;
    outcome: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface OracleBridge extends BaseContract {
  connect(runner?: ContractRunner | null): OracleBridge;
  waitForDeployment(): Promise<this>;

  interface: OracleBridgeInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  CONSENSUS_THRESHOLD: TypedContractMethod<[], [bigint], "view">;

  MIN_ORACLES: TypedContractMethod<[], [bigint], "view">;

  MIN_STAKE: TypedContractMethod<[], [bigint], "view">;

  deactivateOracle: TypedContractMethod<
    [oracle: AddressLike],
    [void],
    "nonpayable"
  >;

  getActiveOraclesCount: TypedContractMethod<[], [bigint], "view">;

  getOracle: TypedContractMethod<
    [oracle: AddressLike],
    [OracleBridge.OracleStructOutput],
    "view"
  >;

  getResolution: TypedContractMethod<
    [marketId: BigNumberish],
    [OracleBridge.ResolutionStructOutput],
    "view"
  >;

  marketOracles: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [string],
    "view"
  >;

  oracleVotes: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [string],
    "view"
  >;

  oracles: TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, boolean, bigint, bigint, bigint, bigint] & {
        oracle: string;
        isActive: boolean;
        stake: bigint;
        reputation: bigint;
        totalResolutions: bigint;
        correctResolutions: bigint;
      }
    ],
    "view"
  >;

  orxToken: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  raiseDispute: TypedContractMethod<
    [marketId: BigNumberish],
    [void],
    "nonpayable"
  >;

  registerOracle: TypedContractMethod<
    [stakeAmount: BigNumberish],
    [void],
    "nonpayable"
  >;

  registeredOracles: TypedContractMethod<
    [arg0: BigNumberish],
    [string],
    "view"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  resolutions: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, bigint, bigint, boolean, boolean] & {
        marketId: bigint;
        outcome: string;
        confidence: bigint;
        timestamp: bigint;
        disputed: boolean;
        finalized: boolean;
      }
    ],
    "view"
  >;

  submitResolution: TypedContractMethod<
    [marketId: BigNumberish, outcome: BytesLike, confidence: BigNumberish],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "CONSENSUS_THRESHOLD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MIN_ORACLES"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MIN_STAKE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "deactivateOracle"
  ): TypedContractMethod<[oracle: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getActiveOraclesCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getOracle"
  ): TypedContractMethod<
    [oracle: AddressLike],
    [OracleBridge.OracleStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getResolution"
  ): TypedContractMethod<
    [marketId: BigNumberish],
    [OracleBridge.ResolutionStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "marketOracles"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "oracleVotes"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "oracles"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, boolean, bigint, bigint, bigint, bigint] & {
        oracle: string;
        isActive: boolean;
        stake: bigint;
        reputation: bigint;
        totalResolutions: bigint;
        correctResolutions: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "orxToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "raiseDispute"
  ): TypedContractMethod<[marketId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "registerOracle"
  ): TypedContractMethod<[stakeAmount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "registeredOracles"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "resolutions"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, bigint, bigint, boolean, boolean] & {
        marketId: bigint;
        outcome: string;
        confidence: bigint;
        timestamp: bigint;
        disputed: boolean;
        finalized: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "submitResolution"
  ): TypedContractMethod<
    [marketId: BigNumberish, outcome: BytesLike, confidence: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "DisputeRaised"
  ): TypedContractEvent<
    DisputeRaisedEvent.InputTuple,
    DisputeRaisedEvent.OutputTuple,
    DisputeRaisedEvent.OutputObject
  >;
  getEvent(
    key: "OracleDeactivated"
  ): TypedContractEvent<
    OracleDeactivatedEvent.InputTuple,
    OracleDeactivatedEvent.OutputTuple,
    OracleDeactivatedEvent.OutputObject
  >;
  getEvent(
    key: "OracleRegistered"
  ): TypedContractEvent<
    OracleRegisteredEvent.InputTuple,
    OracleRegisteredEvent.OutputTuple,
    OracleRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "ResolutionFinalized"
  ): TypedContractEvent<
    ResolutionFinalizedEvent.InputTuple,
    ResolutionFinalizedEvent.OutputTuple,
    ResolutionFinalizedEvent.OutputObject
  >;
  getEvent(
    key: "ResolutionSubmitted"
  ): TypedContractEvent<
    ResolutionSubmittedEvent.InputTuple,
    ResolutionSubmittedEvent.OutputTuple,
    ResolutionSubmittedEvent.OutputObject
  >;

  filters: {
    "DisputeRaised(uint256,address)": TypedContractEvent<
      DisputeRaisedEvent.InputTuple,
      DisputeRaisedEvent.OutputTuple,
      DisputeRaisedEvent.OutputObject
    >;
    DisputeRaised: TypedContractEvent<
      DisputeRaisedEvent.InputTuple,
      DisputeRaisedEvent.OutputTuple,
      DisputeRaisedEvent.OutputObject
    >;

    "OracleDeactivated(address)": TypedContractEvent<
      OracleDeactivatedEvent.InputTuple,
      OracleDeactivatedEvent.OutputTuple,
      OracleDeactivatedEvent.OutputObject
    >;
    OracleDeactivated: TypedContractEvent<
      OracleDeactivatedEvent.InputTuple,
      OracleDeactivatedEvent.OutputTuple,
      OracleDeactivatedEvent.OutputObject
    >;

    "OracleRegistered(address,uint256)": TypedContractEvent<
      OracleRegisteredEvent.InputTuple,
      OracleRegisteredEvent.OutputTuple,
      OracleRegisteredEvent.OutputObject
    >;
    OracleRegistered: TypedContractEvent<
      OracleRegisteredEvent.InputTuple,
      OracleRegisteredEvent.OutputTuple,
      OracleRegisteredEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "ResolutionFinalized(uint256,bytes32)": TypedContractEvent<
      ResolutionFinalizedEvent.InputTuple,
      ResolutionFinalizedEvent.OutputTuple,
      ResolutionFinalizedEvent.OutputObject
    >;
    ResolutionFinalized: TypedContractEvent<
      ResolutionFinalizedEvent.InputTuple,
      ResolutionFinalizedEvent.OutputTuple,
      ResolutionFinalizedEvent.OutputObject
    >;

    "ResolutionSubmitted(uint256,address,bytes32)": TypedContractEvent<
      ResolutionSubmittedEvent.InputTuple,
      ResolutionSubmittedEvent.OutputTuple,
      ResolutionSubmittedEvent.OutputObject
    >;
    ResolutionSubmitted: TypedContractEvent<
      ResolutionSubmittedEvent.InputTuple,
      ResolutionSubmittedEvent.OutputTuple,
      ResolutionSubmittedEvent.OutputObject
    >;
  };
}
