/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace PredictionMarket {
  export type OutcomeStruct = {
    name: string;
    totalStaked: BigNumberish;
    betCount: BigNumberish;
  };

  export type OutcomeStructOutput = [
    name: string,
    totalStaked: bigint,
    betCount: bigint
  ] & { name: string; totalStaked: bigint; betCount: bigint };

  export type BetStruct = {
    amount: BigNumberish;
    outcome: BigNumberish;
    timestamp: BigNumberish;
    claimed: boolean;
  };

  export type BetStructOutput = [
    amount: bigint,
    outcome: bigint,
    timestamp: bigint,
    claimed: boolean
  ] & { amount: bigint; outcome: bigint; timestamp: bigint; claimed: boolean };
}

export interface PredictionMarketInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "calculateUserReward"
      | "cancelMarket"
      | "claimReward"
      | "creator"
      | "description"
      | "disputeMarket"
      | "expiryTime"
      | "factory"
      | "getMarketInfo"
      | "getOdds"
      | "getOutcomes"
      | "getParticipants"
      | "getUserBets"
      | "hasParticipated"
      | "hasUnclaimedRewards"
      | "oracleAddress"
      | "oracleType"
      | "outcomeStaked"
      | "outcomes"
      | "participants"
      | "pause"
      | "paused"
      | "placeBet"
      | "platformFeeRate"
      | "resolutionTime"
      | "resolveMarket"
      | "status"
      | "title"
      | "totalVolume"
      | "unpause"
      | "userBets"
      | "userTotalStaked"
      | "winningOutcome"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BetPlaced"
      | "MarketCancelled"
      | "MarketDisputed"
      | "MarketResolved"
      | "Paused"
      | "RewardClaimed"
      | "Unpaused"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "calculateUserReward",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelMarket",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "claimReward",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "creator", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "description",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "disputeMarket",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "expiryTime",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "factory", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getMarketInfo",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "getOdds", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getOutcomes",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getParticipants",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getUserBets",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasParticipated",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasUnclaimedRewards",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "oracleAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "oracleType",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "outcomeStaked",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "outcomes",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "participants",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "placeBet",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "platformFeeRate",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "resolutionTime",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "resolveMarket",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(functionFragment: "status", values?: undefined): string;
  encodeFunctionData(functionFragment: "title", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "totalVolume",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "userBets",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "userTotalStaked",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "winningOutcome",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "calculateUserReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelMarket",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "creator", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "description",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "disputeMarket",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "expiryTime", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "factory", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getMarketInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getOdds", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getOutcomes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getParticipants",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserBets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasParticipated",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasUnclaimedRewards",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "oracleAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "oracleType", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "outcomeStaked",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "outcomes", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "participants",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "placeBet", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "platformFeeRate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "resolutionTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "resolveMarket",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "status", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "title", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalVolume",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "userBets", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "userTotalStaked",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "winningOutcome",
    data: BytesLike
  ): Result;
}

export namespace BetPlacedEvent {
  export type InputTuple = [
    user: AddressLike,
    outcome: BigNumberish,
    amount: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    outcome: bigint,
    amount: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    user: string;
    outcome: bigint;
    amount: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MarketCancelledEvent {
  export type InputTuple = [timestamp: BigNumberish, reason: string];
  export type OutputTuple = [timestamp: bigint, reason: string];
  export interface OutputObject {
    timestamp: bigint;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MarketDisputedEvent {
  export type InputTuple = [
    disputer: AddressLike,
    timestamp: BigNumberish,
    reason: string
  ];
  export type OutputTuple = [
    disputer: string,
    timestamp: bigint,
    reason: string
  ];
  export interface OutputObject {
    disputer: string;
    timestamp: bigint;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MarketResolvedEvent {
  export type InputTuple = [
    winningOutcome: BigNumberish,
    timestamp: BigNumberish,
    resolution: string
  ];
  export type OutputTuple = [
    winningOutcome: bigint,
    timestamp: bigint,
    resolution: string
  ];
  export interface OutputObject {
    winningOutcome: bigint;
    timestamp: bigint;
    resolution: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RewardClaimedEvent {
  export type InputTuple = [
    user: AddressLike,
    amount: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [user: string, amount: bigint, timestamp: bigint];
  export interface OutputObject {
    user: string;
    amount: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PredictionMarket extends BaseContract {
  connect(runner?: ContractRunner | null): PredictionMarket;
  waitForDeployment(): Promise<this>;

  interface: PredictionMarketInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  calculateUserReward: TypedContractMethod<
    [_user: AddressLike],
    [bigint],
    "view"
  >;

  cancelMarket: TypedContractMethod<[_reason: string], [void], "nonpayable">;

  claimReward: TypedContractMethod<[], [void], "nonpayable">;

  creator: TypedContractMethod<[], [string], "view">;

  description: TypedContractMethod<[], [string], "view">;

  disputeMarket: TypedContractMethod<[_reason: string], [void], "payable">;

  expiryTime: TypedContractMethod<[], [bigint], "view">;

  factory: TypedContractMethod<[], [string], "view">;

  getMarketInfo: TypedContractMethod<
    [],
    [
      [string, string, bigint, bigint, bigint, bigint, bigint] & {
        _title: string;
        _description: string;
        _totalVolume: bigint;
        _expiryTime: bigint;
        _status: bigint;
        _participantCount: bigint;
        _outcomeCount: bigint;
      }
    ],
    "view"
  >;

  getOdds: TypedContractMethod<[], [bigint[]], "view">;

  getOutcomes: TypedContractMethod<
    [],
    [PredictionMarket.OutcomeStructOutput[]],
    "view"
  >;

  getParticipants: TypedContractMethod<[], [string[]], "view">;

  getUserBets: TypedContractMethod<
    [_user: AddressLike],
    [PredictionMarket.BetStructOutput[]],
    "view"
  >;

  hasParticipated: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  hasUnclaimedRewards: TypedContractMethod<
    [_user: AddressLike],
    [boolean],
    "view"
  >;

  oracleAddress: TypedContractMethod<[], [string], "view">;

  oracleType: TypedContractMethod<[], [bigint], "view">;

  outcomeStaked: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  outcomes: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, bigint] & {
        name: string;
        totalStaked: bigint;
        betCount: bigint;
      }
    ],
    "view"
  >;

  participants: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  placeBet: TypedContractMethod<[_outcome: BigNumberish], [void], "payable">;

  platformFeeRate: TypedContractMethod<[], [bigint], "view">;

  resolutionTime: TypedContractMethod<[], [bigint], "view">;

  resolveMarket: TypedContractMethod<
    [_winningOutcome: BigNumberish, _resolution: string],
    [void],
    "nonpayable"
  >;

  status: TypedContractMethod<[], [bigint], "view">;

  title: TypedContractMethod<[], [string], "view">;

  totalVolume: TypedContractMethod<[], [bigint], "view">;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  userBets: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [
      [bigint, bigint, bigint, boolean] & {
        amount: bigint;
        outcome: bigint;
        timestamp: bigint;
        claimed: boolean;
      }
    ],
    "view"
  >;

  userTotalStaked: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  winningOutcome: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "calculateUserReward"
  ): TypedContractMethod<[_user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "cancelMarket"
  ): TypedContractMethod<[_reason: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimReward"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "creator"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "description"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "disputeMarket"
  ): TypedContractMethod<[_reason: string], [void], "payable">;
  getFunction(
    nameOrSignature: "expiryTime"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "factory"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getMarketInfo"
  ): TypedContractMethod<
    [],
    [
      [string, string, bigint, bigint, bigint, bigint, bigint] & {
        _title: string;
        _description: string;
        _totalVolume: bigint;
        _expiryTime: bigint;
        _status: bigint;
        _participantCount: bigint;
        _outcomeCount: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getOdds"
  ): TypedContractMethod<[], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getOutcomes"
  ): TypedContractMethod<[], [PredictionMarket.OutcomeStructOutput[]], "view">;
  getFunction(
    nameOrSignature: "getParticipants"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getUserBets"
  ): TypedContractMethod<
    [_user: AddressLike],
    [PredictionMarket.BetStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasParticipated"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "hasUnclaimedRewards"
  ): TypedContractMethod<[_user: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "oracleAddress"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "oracleType"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "outcomeStaked"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "outcomes"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, bigint] & {
        name: string;
        totalStaked: bigint;
        betCount: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "participants"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "placeBet"
  ): TypedContractMethod<[_outcome: BigNumberish], [void], "payable">;
  getFunction(
    nameOrSignature: "platformFeeRate"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "resolutionTime"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "resolveMarket"
  ): TypedContractMethod<
    [_winningOutcome: BigNumberish, _resolution: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "status"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "title"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "totalVolume"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "userBets"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [
      [bigint, bigint, bigint, boolean] & {
        amount: bigint;
        outcome: bigint;
        timestamp: bigint;
        claimed: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "userTotalStaked"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "winningOutcome"
  ): TypedContractMethod<[], [bigint], "view">;

  getEvent(
    key: "BetPlaced"
  ): TypedContractEvent<
    BetPlacedEvent.InputTuple,
    BetPlacedEvent.OutputTuple,
    BetPlacedEvent.OutputObject
  >;
  getEvent(
    key: "MarketCancelled"
  ): TypedContractEvent<
    MarketCancelledEvent.InputTuple,
    MarketCancelledEvent.OutputTuple,
    MarketCancelledEvent.OutputObject
  >;
  getEvent(
    key: "MarketDisputed"
  ): TypedContractEvent<
    MarketDisputedEvent.InputTuple,
    MarketDisputedEvent.OutputTuple,
    MarketDisputedEvent.OutputObject
  >;
  getEvent(
    key: "MarketResolved"
  ): TypedContractEvent<
    MarketResolvedEvent.InputTuple,
    MarketResolvedEvent.OutputTuple,
    MarketResolvedEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "RewardClaimed"
  ): TypedContractEvent<
    RewardClaimedEvent.InputTuple,
    RewardClaimedEvent.OutputTuple,
    RewardClaimedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;

  filters: {
    "BetPlaced(address,uint256,uint256,uint256)": TypedContractEvent<
      BetPlacedEvent.InputTuple,
      BetPlacedEvent.OutputTuple,
      BetPlacedEvent.OutputObject
    >;
    BetPlaced: TypedContractEvent<
      BetPlacedEvent.InputTuple,
      BetPlacedEvent.OutputTuple,
      BetPlacedEvent.OutputObject
    >;

    "MarketCancelled(uint256,string)": TypedContractEvent<
      MarketCancelledEvent.InputTuple,
      MarketCancelledEvent.OutputTuple,
      MarketCancelledEvent.OutputObject
    >;
    MarketCancelled: TypedContractEvent<
      MarketCancelledEvent.InputTuple,
      MarketCancelledEvent.OutputTuple,
      MarketCancelledEvent.OutputObject
    >;

    "MarketDisputed(address,uint256,string)": TypedContractEvent<
      MarketDisputedEvent.InputTuple,
      MarketDisputedEvent.OutputTuple,
      MarketDisputedEvent.OutputObject
    >;
    MarketDisputed: TypedContractEvent<
      MarketDisputedEvent.InputTuple,
      MarketDisputedEvent.OutputTuple,
      MarketDisputedEvent.OutputObject
    >;

    "MarketResolved(uint256,uint256,string)": TypedContractEvent<
      MarketResolvedEvent.InputTuple,
      MarketResolvedEvent.OutputTuple,
      MarketResolvedEvent.OutputObject
    >;
    MarketResolved: TypedContractEvent<
      MarketResolvedEvent.InputTuple,
      MarketResolvedEvent.OutputTuple,
      MarketResolvedEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "RewardClaimed(address,uint256,uint256)": TypedContractEvent<
      RewardClaimedEvent.InputTuple,
      RewardClaimedEvent.OutputTuple,
      RewardClaimedEvent.OutputObject
    >;
    RewardClaimed: TypedContractEvent<
      RewardClaimedEvent.InputTuple,
      RewardClaimedEvent.OutputTuple,
      RewardClaimedEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
  };
}
