/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace PredictionMarketFactory {
  export type MarketInfoStruct = {
    marketAddress: AddressLike;
    title: string;
    description: string;
    createdAt: BigNumberish;
    expiryTime: BigNumberish;
    isActive: boolean;
    creator: AddressLike;
    category: string;
  };

  export type MarketInfoStructOutput = [
    marketAddress: string,
    title: string,
    description: string,
    createdAt: bigint,
    expiryTime: bigint,
    isActive: boolean,
    creator: string,
    category: string
  ] & {
    marketAddress: string;
    title: string;
    description: string;
    createdAt: bigint;
    expiryTime: bigint;
    isActive: boolean;
    creator: string;
    category: string;
  };
}

export interface PredictionMarketFactoryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "categoryMarkets"
      | "createMarket"
      | "getActiveMarkets"
      | "getMarket"
      | "getMarkets"
      | "getMarketsByCategory"
      | "getTotalMarkets"
      | "getUserMarkets"
      | "marketCounter"
      | "marketCreationFee"
      | "marketExists"
      | "markets"
      | "oracleAddress"
      | "owner"
      | "renounceOwnership"
      | "setStakingContract"
      | "stakingContract"
      | "toggleMarketStatus"
      | "transferOwnership"
      | "updateConfig"
      | "userMarkets"
      | "withdrawFees"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "FactoryConfigUpdated"
      | "MarketCreated"
      | "MarketStatusChanged"
      | "OwnershipTransferred"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "categoryMarkets",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createMarket",
    values: [string, string, string[], BigNumberish, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getActiveMarkets",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getMarket",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getMarkets",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getMarketsByCategory",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalMarkets",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getUserMarkets",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "marketCounter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "marketCreationFee",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "marketExists",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "markets",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "oracleAddress",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setStakingContract",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "stakingContract",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "toggleMarketStatus",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateConfig",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "userMarkets",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawFees",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "categoryMarkets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createMarket",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getActiveMarkets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getMarket", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getMarkets", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getMarketsByCategory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalMarkets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserMarkets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "marketCounter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "marketCreationFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "marketExists",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "markets", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "oracleAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setStakingContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "stakingContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "toggleMarketStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateConfig",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userMarkets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawFees",
    data: BytesLike
  ): Result;
}

export namespace FactoryConfigUpdatedEvent {
  export type InputTuple = [
    marketCreationFee: BigNumberish,
    oracleAddress: AddressLike
  ];
  export type OutputTuple = [marketCreationFee: bigint, oracleAddress: string];
  export interface OutputObject {
    marketCreationFee: bigint;
    oracleAddress: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MarketCreatedEvent {
  export type InputTuple = [
    marketId: BigNumberish,
    marketAddress: AddressLike,
    creator: AddressLike,
    title: string,
    category: string,
    expiryTime: BigNumberish
  ];
  export type OutputTuple = [
    marketId: bigint,
    marketAddress: string,
    creator: string,
    title: string,
    category: string,
    expiryTime: bigint
  ];
  export interface OutputObject {
    marketId: bigint;
    marketAddress: string;
    creator: string;
    title: string;
    category: string;
    expiryTime: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MarketStatusChangedEvent {
  export type InputTuple = [marketId: BigNumberish, isActive: boolean];
  export type OutputTuple = [marketId: bigint, isActive: boolean];
  export interface OutputObject {
    marketId: bigint;
    isActive: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PredictionMarketFactory extends BaseContract {
  connect(runner?: ContractRunner | null): PredictionMarketFactory;
  waitForDeployment(): Promise<this>;

  interface: PredictionMarketFactoryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  categoryMarkets: TypedContractMethod<
    [arg0: string, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  createMarket: TypedContractMethod<
    [
      _title: string,
      _description: string,
      _outcomes: string[],
      _expiryTime: BigNumberish,
      _category: string,
      _oracleType: BigNumberish
    ],
    [string],
    "payable"
  >;

  getActiveMarkets: TypedContractMethod<
    [_offset: BigNumberish, _limit: BigNumberish],
    [PredictionMarketFactory.MarketInfoStructOutput[]],
    "view"
  >;

  getMarket: TypedContractMethod<
    [_marketId: BigNumberish],
    [PredictionMarketFactory.MarketInfoStructOutput],
    "view"
  >;

  getMarkets: TypedContractMethod<
    [_offset: BigNumberish, _limit: BigNumberish],
    [PredictionMarketFactory.MarketInfoStructOutput[]],
    "view"
  >;

  getMarketsByCategory: TypedContractMethod<
    [_category: string],
    [bigint[]],
    "view"
  >;

  getTotalMarkets: TypedContractMethod<[], [bigint], "view">;

  getUserMarkets: TypedContractMethod<[_user: AddressLike], [bigint[]], "view">;

  marketCounter: TypedContractMethod<[], [bigint], "view">;

  marketCreationFee: TypedContractMethod<[], [bigint], "view">;

  marketExists: TypedContractMethod<
    [_marketId: BigNumberish],
    [boolean],
    "view"
  >;

  markets: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, string, bigint, bigint, boolean, string, string] & {
        marketAddress: string;
        title: string;
        description: string;
        createdAt: bigint;
        expiryTime: bigint;
        isActive: boolean;
        creator: string;
        category: string;
      }
    ],
    "view"
  >;

  oracleAddress: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setStakingContract: TypedContractMethod<
    [_stakingContract: AddressLike],
    [void],
    "nonpayable"
  >;

  stakingContract: TypedContractMethod<[], [string], "view">;

  toggleMarketStatus: TypedContractMethod<
    [_marketId: BigNumberish],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  updateConfig: TypedContractMethod<
    [_marketCreationFee: BigNumberish, _oracleAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  userMarkets: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  withdrawFees: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "categoryMarkets"
  ): TypedContractMethod<[arg0: string, arg1: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "createMarket"
  ): TypedContractMethod<
    [
      _title: string,
      _description: string,
      _outcomes: string[],
      _expiryTime: BigNumberish,
      _category: string,
      _oracleType: BigNumberish
    ],
    [string],
    "payable"
  >;
  getFunction(
    nameOrSignature: "getActiveMarkets"
  ): TypedContractMethod<
    [_offset: BigNumberish, _limit: BigNumberish],
    [PredictionMarketFactory.MarketInfoStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getMarket"
  ): TypedContractMethod<
    [_marketId: BigNumberish],
    [PredictionMarketFactory.MarketInfoStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getMarkets"
  ): TypedContractMethod<
    [_offset: BigNumberish, _limit: BigNumberish],
    [PredictionMarketFactory.MarketInfoStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getMarketsByCategory"
  ): TypedContractMethod<[_category: string], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getTotalMarkets"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getUserMarkets"
  ): TypedContractMethod<[_user: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "marketCounter"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "marketCreationFee"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "marketExists"
  ): TypedContractMethod<[_marketId: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "markets"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, string, bigint, bigint, boolean, string, string] & {
        marketAddress: string;
        title: string;
        description: string;
        createdAt: bigint;
        expiryTime: bigint;
        isActive: boolean;
        creator: string;
        category: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "oracleAddress"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setStakingContract"
  ): TypedContractMethod<[_stakingContract: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "stakingContract"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "toggleMarketStatus"
  ): TypedContractMethod<[_marketId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateConfig"
  ): TypedContractMethod<
    [_marketCreationFee: BigNumberish, _oracleAddress: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "userMarkets"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "withdrawFees"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "FactoryConfigUpdated"
  ): TypedContractEvent<
    FactoryConfigUpdatedEvent.InputTuple,
    FactoryConfigUpdatedEvent.OutputTuple,
    FactoryConfigUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "MarketCreated"
  ): TypedContractEvent<
    MarketCreatedEvent.InputTuple,
    MarketCreatedEvent.OutputTuple,
    MarketCreatedEvent.OutputObject
  >;
  getEvent(
    key: "MarketStatusChanged"
  ): TypedContractEvent<
    MarketStatusChangedEvent.InputTuple,
    MarketStatusChangedEvent.OutputTuple,
    MarketStatusChangedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "FactoryConfigUpdated(uint256,address)": TypedContractEvent<
      FactoryConfigUpdatedEvent.InputTuple,
      FactoryConfigUpdatedEvent.OutputTuple,
      FactoryConfigUpdatedEvent.OutputObject
    >;
    FactoryConfigUpdated: TypedContractEvent<
      FactoryConfigUpdatedEvent.InputTuple,
      FactoryConfigUpdatedEvent.OutputTuple,
      FactoryConfigUpdatedEvent.OutputObject
    >;

    "MarketCreated(uint256,address,address,string,string,uint256)": TypedContractEvent<
      MarketCreatedEvent.InputTuple,
      MarketCreatedEvent.OutputTuple,
      MarketCreatedEvent.OutputObject
    >;
    MarketCreated: TypedContractEvent<
      MarketCreatedEvent.InputTuple,
      MarketCreatedEvent.OutputTuple,
      MarketCreatedEvent.OutputObject
    >;

    "MarketStatusChanged(uint256,bool)": TypedContractEvent<
      MarketStatusChangedEvent.InputTuple,
      MarketStatusChangedEvent.OutputTuple,
      MarketStatusChangedEvent.OutputObject
    >;
    MarketStatusChanged: TypedContractEvent<
      MarketStatusChangedEvent.InputTuple,
      MarketStatusChangedEvent.OutputTuple,
      MarketStatusChangedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
