/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface IAIOracleInterface extends Interface {
  getFunction(
    nameOrSignature: "getAIResult" | "submitAIResult"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getAIResult",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "submitAIResult",
    values: [AddressLike, BigNumberish, BigNumberish, string]
  ): string;

  decodeFunctionResult(
    functionFragment: "getAIResult",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitAIResult",
    data: BytesLike
  ): Result;
}

export interface IAIOracle extends BaseContract {
  connect(runner?: ContractRunner | null): IAIOracle;
  waitForDeployment(): Promise<this>;

  interface: IAIOracleInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getAIResult: TypedContractMethod<
    [_market: AddressLike],
    [
      [bigint, bigint, boolean] & {
        outcome: bigint;
        confidence: bigint;
        isSubmitted: boolean;
      }
    ],
    "view"
  >;

  submitAIResult: TypedContractMethod<
    [
      _market: AddressLike,
      _predictedOutcome: BigNumberish,
      _confidence: BigNumberish,
      _evidence: string
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getAIResult"
  ): TypedContractMethod<
    [_market: AddressLike],
    [
      [bigint, bigint, boolean] & {
        outcome: bigint;
        confidence: bigint;
        isSubmitted: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "submitAIResult"
  ): TypedContractMethod<
    [
      _market: AddressLike,
      _predictedOutcome: BigNumberish,
      _confidence: BigNumberish,
      _evidence: string
    ],
    [void],
    "nonpayable"
  >;

  filters: {};
}
